name: Sphinx Docs
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip sphinx-autodoc-typehints sphinx_example_includer sphinx docutils
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Remove docs folder
      run: |
        rm -Rf docs
    - name: Generate documentation
      run: |
        python -m sphinx_example_includer --info --build --project src --files examples/*example*.py --overwrite
        cd docs; ls;find . -maxdepth 1 ! -name '_build' ! -name '.' ! -name '..' -exec rm -rf {} +
        mv _build/html/* ./
        touch .nojekyll
        cd ..
    - name: Configure Git
      run: |
        git config --global user.name "yourusername"
        git config --global user.email "youremail@users.noreply.github.com"
    - name: Commit changes
      run: |
        git status -u
        git add docs
        git commit -m "update docs"
    - name: Push changes
      run: |
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}